const CAT={snack:'お菓子',lunch:'昼メシ',drink:'飲み物'};
const ICON={snack:'🍫',lunch:'🍙',drink:'🥤'};
const SEED=[
{id:'s1',jan:'4900000000016',name:'クリームパン',category:'snack',storePrice:138,netPrice:158,kcal:356,source:'demo'},
{id:'s2',jan:'4900000000023',name:'チョコバー',category:'snack',storePrice:48,netPrice:58,kcal:118,source:'demo'},
{id:'s3',jan:'4900000000030',name:'ミックスナッツ 小袋',category:'snack',storePrice:158,netPrice:178,kcal:186,source:'demo'},
{id:'l1',jan:'4900000000105',name:'カツ丼',category:'lunch',storePrice:498,netPrice:538,kcal:892,source:'demo'},
{id:'l2',jan:'4900000000112',name:'鮭おにぎり + たまごサンド',category:'lunch',storePrice:398,netPrice:438,kcal:486,source:'demo'},
{id:'l3',jan:'4900000000129',name:'おにぎり2個 + ゆでたまご',category:'lunch',storePrice:358,netPrice:398,kcal:421,source:'demo'},
{id:'d1',jan:'4900000000201',name:'コーラ 500ml',category:'drink',storePrice:108,netPrice:128,kcal:225,source:'demo'},
{id:'d2',jan:'4900000000218',name:'無糖茶 600ml',category:'drink',storePrice:88,netPrice:98,kcal:0,source:'demo'},
{id:'d3',jan:'4900000000225',name:'炭酸水 500ml',category:'drink',storePrice:79,netPrice:89,kcal:0,source:'demo'}];
const K={catalog:'sa.catalog',history:'sa.history',stats:'sa.stats'};
const S={route:'today',focus:'drink',fixed:'d1',rec:null,last:null,stream:null,detector:null};
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=n=>n!==null&&n!==''&&Number.isFinite(Number(n))?'¥'+Math.round(Number(n)).toLocaleString('ja-JP'):'—';
const kc=n=>n!==null&&n!==''&&Number.isFinite(Number(n))?Math.round(Number(n))+' kcal':'— kcal';
const date=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now()+'-'+Math.random().toString(36).slice(2,7);
function catalog(){const m=new Map(SEED.map(p=>[p.id,p]));read(K.catalog,[]).forEach(p=>m.set(p.id,p));return Array.from(m.values())}
function saveProduct(p){const a=read(K.catalog,[]);const i=a.findIndex(x=>x.id===p.id||(p.jan&&x.jan===p.jan));if(i>=0)a[i]=p;else a.push(p);write(K.catalog,a)}
function stats(){return read(K.stats,{})}function st(id){return stats()[id]||{proposed:0,selected:0,good:0,meh:0,ng:0}}
function mod(id,key,delta){const a=stats();a[id]=a[id]||{proposed:0,selected:0,good:0,meh:0,ng:0};a[id][key]=Math.max(0,(a[id][key]||0)+delta);write(K.stats,a)}
function ng(id){return st(id).ng>0}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.classList.add('show'),10);setTimeout(()=>e.remove(),1900)}
function score(p){const x=st(p.id),r=x.proposed?x.selected/x.proposed:.45;return r*100+x.good*8-x.meh*7-(Number(p.kcal)||250)/14-(Number(p.storePrice)||200)/20+Math.random()*20}
function pick(c){const a=catalog().filter(p=>p.category===c&&!ng(p.id)).sort((a,b)=>score(b)-score(a));return a[0]||null}
function makeRec(){const r={};Object.keys(CAT).forEach(c=>{let p=c===S.focus?catalog().find(x=>x.id===S.fixed&&!ng(x.id)):null;p=p||pick(c);if(p){r[c]=p;mod(p.id,'proposed',1)}});S.rec=r;return r}
function card(p){const x=st(p.id),rate=x.proposed?Math.round(x.selected/x.proposed*100):0,d=p.netPrice!==null&&p.storePrice!==null&&Number.isFinite(Number(p.netPrice))&&Number.isFinite(Number(p.storePrice))?Number(p.netPrice)-Number(p.storePrice):null;return '<article class="product card"><div class="ico">'+ICON[p.category]+'</div><div class="grow"><div><span class="badge">'+CAT[p.category]+'</span>'+(ng(p.id)?'<span class="badge bad">NG</span>':'')+'</div><b>'+esc(p.name)+'</b><small>店頭 '+yen(p.storePrice)+(d!==null?' / ネット '+yen(p.netPrice)+' (+'+d+'円)':'')+'</small><small>選ばれ率 '+rate+'%</small></div><div class="num"><b>'+yen(p.storePrice)+'</b><small>'+kc(p.kcal)+'</small></div></article>'}
function renderToday(){const r=S.rec||makeRec(),ps=Object.values(r),price=ps.reduce((a,p)=>a+(Number(p.storePrice)||0),0),cal=ps.reduce((a,p)=>a+(Number(p.kcal)||0),0);return '<section class="hero"><small>出勤前の西友だけ</small><h2>今日の3点、これでどう？</h2><p>お菓子 + 昼メシ + ペットボトル。夕方の買い物は混ぜない。</p></section><section class="card focus"><b>今日はこれを固定</b><div class="pills">'+Object.keys(CAT).map(c=>'<button data-focus="'+c+'" class="pill '+(S.focus===c?'on':'')+'">'+CAT[c]+'</button>').join('')+'</div><select id="fixed">'+catalog().filter(p=>p.category===S.focus&&!ng(p.id)).map(p=>'<option value="'+p.id+'" '+(p.id===S.fixed?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></section><div class="title"><h3>今日のセット</h3><button id="reroll">別のセット</button></div>'+ps.map(card).join('')+'<section class="summary"><small>合計</small><strong>'+yen(price)+' / '+kc(cal)+'</strong><p>好きな1品はそのまま。残り2つで価格とカロリーを少し整える。</p></section><button class="primary" id="accept">これでいく</button><button class="secondary" data-jump="scan">商品をスキャンして比べる</button>'}
function accept(){const h=read(K.history,[]);Object.values(S.rec||{}).forEach(p=>{h.push({id:uid(),date:date(),productId:p.id,name:p.name,category:p.category,price:p.storePrice,kcal:p.kcal,status:'planned',feedback:null});mod(p.id,'selected',1)});write(K.history,h);toast('今日の3点に追加しました');S.route='history';render()}
function renderScan(){return '<section class="hero"><small>店頭で迷ったら</small><h2>バーコードで判定</h2><p>JAN/EANを読み、価格・カロリー・西友の候補を比べる。</p></section><section class="card scan"><div class="video"><video id="video" playsinline muted></video><i></i></div><div class="row"><button class="primary small" id="start">カメラで読む</button><button class="secondary small" id="stop">停止</button></div><div class="manual"><input id="jan" inputmode="numeric" placeholder="JANコードを手入力"><button id="lookup">検索</button></div></section><div id="result">'+(S.last?scanResult(S.last):'')+'</div>'}
function scanResult(r){if(r.error)return '<div class="error">'+esc(r.error)+'</div>';const p=r.product,has=p.netPrice!==null&&p.storePrice!==null&&Number.isFinite(Number(p.netPrice))&&Number.isFinite(Number(p.storePrice)),d=has?Number(p.netPrice)-Number(p.storePrice):0;let html='<section class="card result"><span class="badge">JAN '+esc(p.jan)+'</span><h3>'+esc(p.name)+'</h3><div class="metrics"><div><small>店頭</small><b>'+yen(p.storePrice)+'</b></div><div><small>ネット参考</small><b>'+yen(p.netPrice)+'</b></div><div><small>kcal</small><b>'+kc(p.kcal)+'</b></div></div>'+(has?'<p class="callout">'+(d>=0?'店頭のほうが '+yen(d)+' 安い':'ネット参考のほうが '+yen(Math.abs(d))+' 安い')+'</p>':'<p class="hint">価格を登録すると差額を出せます。</p>')+registerForm(p)+'</section>';if(r.seiyu&&r.seiyu.length)html+='<div class="title"><h3>西友ネット候補</h3><span>参考価格</span></div>'+r.seiyu.map(x=>'<a class="hit card" target="_blank" rel="noreferrer" href="'+esc(x.url)+'"><div><b>'+esc(x.name)+'</b><small>'+esc(x.size||'')+'</small></div><strong>'+yen(x.taxIncludedPrice||x.price)+'</strong></a>').join('');else html+='<a class="searchlink" target="_blank" rel="noreferrer" href="'+seiyuUrl(p.name)+'">西友ネットスーパーで検索 →</a>';const alt=catalog().filter(x=>x.category===p.category&&x.id!==p.id&&!ng(x.id)).sort((a,b)=>(Number(a.kcal)||9999)-(Number(b.kcal)||9999)).slice(0,3);if(alt.length)html+='<div class="title"><h3>代わりにこれ</h3></div>'+alt.map(card).join('');return html}
function registerForm(p){return '<form id="register" class="form"><input type="hidden" name="jan" value="'+esc(p.jan)+'"><input type="hidden" name="name" value="'+esc(p.name)+'"><label>種類<select name="category">'+Object.keys(CAT).map(c=>'<option value="'+c+'" '+(p.category===c?'selected':'')+'>'+CAT[c]+'</option>').join('')+'</select></label><label>店頭価格<input name="storePrice" type="number" value="'+(p.storePrice==null?'':p.storePrice)+'"></label><label>ネット参考<input name="netPrice" type="number" value="'+(p.netPrice==null?'':p.netPrice)+'"></label><label>kcal<input name="kcal" type="number" value="'+(p.kcal==null?'':Math.round(p.kcal))+'"></label><button class="primary small">西友商品として登録</button></form>'}
function seiyuUrl(q){return 'https://netsuper.rakuten.co.jp/seiyu/search/?keyword='+encodeURIComponent(q||'')}
async function searchSeiyu(q){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),4500),r=await fetch('/api/seiyu/search?q='+encodeURIComponent(q),{signal:c.signal});clearTimeout(t);if(!r.ok)return[];const j=await r.json();return Array.isArray(j.items)?j.items:[]}catch(e){return[]}}
async function lookupJan(jan){jan=String(jan||'').trim();if(!/^d{8,14}$/.test(jan))return{error:'JAN/EANコードを確認してください'};let p=catalog().find(x=>x.jan===jan);if(!p){try{const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(jan)+'.json?fields=product_name,product_name_ja,nutriments');if(r.ok){const j=await r.json(),x=j.product;if(j.status===1&&x){const s=Number(x.nutriments&&x.nutriments['energy-kcal_serving']),h=Number(x.nutriments&&x.nutriments['energy-kcal_100g']);p={id:'jan-'+jan,jan:jan,name:x.product_name_ja||x.product_name||('JAN '+jan),category:'snack',storePrice:null,netPrice:null,kcal:Number.isFinite(s)?s:(Number.isFinite(h)?h:null),source:'openfoodfacts'}}}}catch(e){}if(!p)p={id:'jan-'+jan,jan:jan,name:'JAN '+jan,category:'snack',storePrice:null,netPrice:null,kcal:null,source:'manual'}}return{product:p,seiyu:await searchSeiyu(p.name)}}
async function doLookup(jan){const e=$('#result');if(e)e.innerHTML='<p class="loading">商品を調べています…</p>';S.last=await lookupJan(jan);if(e)e.innerHTML=scanResult(S.last);bind()}
async function startScan(){if(!('BarcodeDetector'in window)){toast('自動読取に未対応です。JAN手入力を使ってください。');return}try{const v=$('#video');S.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});v.srcObject=S.stream;await v.play();S.detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});const loop=async()=>{if(!S.detector)return;try{const a=await S.detector.detect(v);if(a[0]&&a[0].rawValue){stopScan();doLookup(a[0].rawValue);return}}catch(e){}requestAnimationFrame(loop)};loop()}catch(e){toast('カメラを開始できませんでした')}}
function stopScan(){if(S.stream)S.stream.getTracks().forEach(t=>t.stop());S.stream=null;S.detector=null}
function renderHistory(){const a=read(K.history,[]).slice().reverse();return '<section class="hero"><small>後悔も忘れない</small><h2>食べたもの</h2><p>「もう買わない」を残すと次回提案から外す。</p></section>'+(a.length?a.map(h=>'<article class="card hist"><div><b>'+esc(h.name)+'</b><small>'+esc(h.date)+' / '+yen(h.price)+' / '+kc(h.kcal)+'</small></div><div class="actions">'+(h.status==='planned'?'<button data-eat="'+h.id+'">食べた</button>':'<span>食べた</span>')+'<button data-fb="good" data-id="'+h.id+'" class="'+(h.feedback==='good'?'on':'')+'">よかった</button><button data-fb="meh" data-id="'+h.id+'" class="'+(h.feedback==='meh'?'on':'')+'">微妙</button><button data-fb="ng" data-id="'+h.id+'" class="'+(h.feedback==='ng'?'danger':'')+'">もう買わない</button></div></article>').join(''):'<p class="empty">まだ履歴がありません。</p>')}
function renderProducts(){return '<section class="hero"><small>自分専用の西友DB</small><h2>商品辞書</h2><p>選ばれ率・NG・価格差をまとめて確認。</p></section>'+catalog().map(p=>card(p)).join('')}
function feedback(id,type){const a=read(K.history,[]),h=a.find(x=>x.id===id);if(!h)return;if(h.feedback)mod(h.productId,h.feedback,-1);h.feedback=type;mod(h.productId,type,1);write(K.history,a);if(type==='ng')toast('NGにしました。次回提案から外します');render()}
function render(){stopScan();$('#app').innerHTML=S.route==='today'?renderToday():S.route==='scan'?renderScan():S.route==='history'?renderHistory():renderProducts();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===S.route));bind()}
function bind(){$$('.nav-item').forEach(b=>b.onclick=()=>{S.route=b.dataset.route;render()});$$('[data-jump]').forEach(b=>b.onclick=()=>{S.route=b.dataset.jump;render()});$$('[data-focus]').forEach(b=>b.onclick=()=>{S.focus=b.dataset.focus;const p=catalog().find(x=>x.category===S.focus&&!ng(x.id));S.fixed=p?p.id:null;S.rec=null;render()});const f=$('#fixed');if(f)f.onchange=()=>{S.fixed=f.value;S.rec=null;render()};const rr=$('#reroll');if(rr)rr.onclick=()=>{S.rec=null;render()};const ac=$('#accept');if(ac)ac.onclick=accept;const st=$('#start');if(st)st.onclick=startScan;const sp=$('#stop');if(sp)sp.onclick=stopScan;const lu=$('#lookup');if(lu)lu.onclick=()=>doLookup($('#jan').value);const rg=$('#register');if(rg)rg.onsubmit=e=>{e.preventDefault();const d=new FormData(rg),n=v=>v===''?null:Number(v),p={id:'jan-'+d.get('jan'),jan:d.get('jan'),name:d.get('name'),category:d.get('category'),storePrice:n(d.get('storePrice')),netPrice:n(d.get('netPrice')),kcal:n(d.get('kcal')),source:'registered'};saveProduct(p);S.last={product:p,seiyu:S.last&&S.last.seiyu||[]};toast('西友商品として登録しました');render()};$$('[data-eat]').forEach(b=>b.onclick=()=>{const a=read(K.history,[]),h=a.find(x=>x.id===b.dataset.eat);if(h){h.status='eaten';write(K.history,a);render()}});$$('[data-fb]').forEach(b=>b.onclick=()=>feedback(b.dataset.id,b.dataset.fb))}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopScan()});render();
